### ISSUE TITLE
Continuation Section equal symbol

### ISSUE THREAD

**Issue by murataygunn** [CoffeeChaton/vscode-autohotkey-NekoHelp-Old#3]
![image](https://user-images.githubusercontent.com/17836269/196009655-ee06c1e5-a57e-41c7-99bd-b73a5e2a859a.png)

Continuation section doesn't support " := " assignment.

Thanks.

**Comment by CoffeeChaton** [comment]
![Multi-line](https://user-images.githubusercontent.com/63182963/196403241-11e6b5da-1e1b-4061-97bc-d5aa242b7d04.png)
> source from https://www.autohotkey.com/docs/Scripts.htm#continuation

1. Continuation section is support " := " assignment, but need to use `:= "`

2. I provide warnings for all "=" because of this case [diag107](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/master/note/ahk/diag107.ahk) like ![diag107](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/raw/master/note/img/diag107.png)

**Comment by murataygunn** [comment]
Yes. If you use " := " syntax the behavior changes and you have to escape quotation marks. Also, the " = " syntax is valid and isn't an error. Anyways, I admire your efforts on this. Lets make that extension perfect. Thank you very much. I use lots of includes. I keep every class on its own file. Does this effect discovering Class methots?

**Comment by CoffeeChaton** [comment]
> the " = " syntax is valid and isn't an error.

I will fix it before November,  let `Error` ->  `Warning`.

>I keep every class on its own file. Does this effect discovering Class methots?

Not affected, but `go to def` `find all ref` just support `topClass`, only [IntelliSense](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#4-completion-of-class) support `NestedClass` of `Method()` now.

![Completion_class](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/master/image/Completion_class.gif?raw=true)

**Comment by CoffeeChaton** [comment]
> I keep every class on its own file. Does this effect discovering Class methots?

[try it](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/tree/master/note#about-ahk-class)
